language: haxe

haxe:
 - 4.0.0-rc.3
 - development

install:
 - haxelib install utest

script:
 - haxe test.hxml

before_deploy:
 - haxelib install dox
 - haxe doc.hxml

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: doc/out
  on:
    branch: master
    haxe: 4.0.0-rc.3
