language: haxe

haxe:
 - 4.0.0-rc.3
 - development

install:
 - haxelib install travix
 - haxelib install utest
 - haxelib run travix install

script:
 - haxelib run travix interp
#  - haxelib run travix neko
#  - haxelib run travix python
 - haxelib run travix node
 - haxelib run travix js
 - haxelib run travix flash
#  - haxelib run travix java
 - haxelib run travix cpp
#  - haxelib run travix cs
#  - haxelib run travix php
#  - haxelib run travix php7
#  - haxelib run travix lua

before_deploy:
 - haxelib install dox
 - haxe doc.hxml

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: doc/out
  on:
    branch: master
    haxe: 4.0.0-rc.3
